[workspace]
members = ["crm"]
resolver = "2"


[workspace.dependencies]
anyhow = "1.0.98"
prost = "0.13.5"
prost-build = "0.13.5"
prost-types = "0.13.5"
tonic = "0.13.1"
tonic-build = "0.13.1"
tokio = { version = "1.45.0", features = ["rt", "rt-multi-thread", "macros"] }
